# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eaodPp-YLfAM_ZWZFEUePT23jTHMMfrm
"""

resposta = input("Deseja continuar no sistema? (sim/não): ")
if resposta.lower() == "sim":
    print("Continuando.")
else:
    print("Encerrando.")

uf = input("Digite a sigla do seu estado (ex: sp, rj, mg):")

print(f"Estado cadastrado: {uf}")

CUPOM_CORRETO = "DESCONTO10"
cupom_usuario = input("Digite o seu cupom promocional: ")

if cupom_usuario.upper() == CUPOM_CORRETO:
    print("Cupom aplicado com sucesso!")
else:
    print("Cupom inválido.")

nome_bruto = input("Digite o seu primeiro nome: ")
nome_limpo = nome_bruto.strip()
total_caracteres = len(nome_limpo)

print(f"Nome limpo: {nome_limpo}")
print(f"Quantidade de caracteres: {total_caracteres}")